version: '3'
services:
  web:
    image: aronpc/cati-php:8.1-nginx
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - mysql
    ports:
      - '8085:8080'

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
    volumes:
      - mysql:/data/mysql

  adminer:
    image: adminer
    ports:
      - '8099:8080'

volumes:
  mysql:
